plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
    id 'maven-publish'
}

version = "${project.mod_version}+${project.minecraft_version}"
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenLocal()

    maven {
        url = uri('https://pkg.mschae23.de/maven')
    }

    maven {
        url = 'https://repo.codemc.io/repository/relativitymc/'
    }

    maven {
        name "Nucleoid"
        url "https://maven.nucleoid.xyz/"
    }

    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "org.relativitymc:modern-yarn:$project.yarn_mappings:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    [
        "fabric-api-base",
        "fabric-registry-sync-v0",
        "fabric-command-api-v2",
        "fabric-entity-events-v1",
        "fabric-lifecycle-events-v1",
        "fabric-message-api-v1",
        "fabric-events-interaction-v0"
    ].forEach { modImplementation fabricApi.module(it, project.fabric_api_version) }

    modImplementation "de.mschae23:codec-config-api:${project.codec_config_api_version}"
    include "de.mschae23:codec-config-api:${project.codec_config_api_version}"

    modImplementation "net.luckperms:api:${project.luckperms_api_version}"
    modImplementation "me.lucko:fabric-permissions-api:${project.permission_api_version}"

    // modImplementation "eu.pb4:placeholder-api:${project.placeholder_api_version}"
    // include "eu.pb4:placeholder-api:${project.placeholder_api_version}"
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand 'version': project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

loom {
    useIntermediateMappings = true
    intermediaryUrl = 'https://repo.codemc.io/repository/relativitymc/org/relativitymc/intermediary/%1$s/intermediary-%1$s-v2.jar'

    accessWidenerPath = file('src/main/resources/regionprotection.accesswidener')

    decompilers {
        vineflower {
            options.put("ind", "    ")
            options.put("nls", "1")
        }
    }
}

java {
    withSourcesJar()
}

jar {
    from('COPYING')
    from('COPYING.LESSER')
}

publishing {
    publications {
        mod(MavenPublication) {
            from components.java
        }
    }

    repositories {
        maven {
            name = "Forgejo"
            url = uri("https://pkg.mschae23.de/maven")

            credentials(HttpHeaderCredentials) {
                final token = java.util.Optional.ofNullable(System.getenv("XDG_CONFIG_HOME")).map { java.nio.file.Path.of(it).resolve("packages") }.or {
                    java.util.Optional.ofNullable(System.getenv("HOME")).map { java.nio.file.Path.of(it).resolve(".config/packages") }}.or {
                    java.util.Optional.ofNullable(System.getenv("HOMEDRIVE")).flatMap { drive -> java.util.Optional.ofNullable(System.getenv("HOMEPATH"))
                        .map { drive + it }}.map { java.nio.file.Path.of(it).resolve(".packages") }}.map {
                    it.resolve("mschae23-forgejo.token") }.filter { java.nio.file.Files.exists(it) }.map {
                    java.nio.file.Files.readString(it, java.nio.charset.StandardCharsets.UTF_8)
                }.orElse("")

                name = "Authorization"
                value = "token $token"
            }

            authentication {
                header(HttpHeaderAuthentication)
            }
        }
    }
}
