# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric properties
# check these on https://fabricmc.net/develop
    minecraft_version=26.1.2
    loader_version=0.19.3
    loom_version=1.16-SNAPSHOT

    yarn_mappings=26.1.2+build.3

# Mod properties
    mod_version = 3.0.0
    maven_group = de.mschae23
    archives_base_name = region-protection

# Dependencies
    fabric_api_version=0.151.0+26.1.2
    codec_config_api_version=3.1.0+26.1
    luckperms_api_version=5.5
    permission_api_version=0.7.0
